In [ ]:
# 1. Importaciones necesarias
import numpy as np
from tensorflow.keras.datasets import mnist  # Para cargar MNIST
from sklearn.naive_bayes import GaussianNB   # Para Naive Bayes
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
# 2. Cargar los datos de MNIST
#mnist.load_data() #devuelve dos tuplas: (x_train, y_train), (x_test, y_test)
# donde x contiene las imágenes y y las etiquetas (dígitos de 0 a 9).
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
# 3. Preprocesamiento
# - Convertimos las imágenes de 28x28 a vectores de 784 dimensiones (flatten).
# - Convertimos de enteros a float para normalizar.
# - Escalamos al rango [0,1] dividiendo entre 255.

x_train = x_train.reshape(-1, 28*28).astype('float32') / 255.0
x_test  = x_test.reshape(-1, 28*28).astype('float32') / 255.0

In [ ]:
# 4. Definir y entrenar el modelo Naive Bayes
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [ ]:
# 5. Realizar predicciones sobre el conjunto de prueba
y_pred = gnb.predict(x_test)

In [ ]:
# 6. Evaluación del modelo
accuracy = accuracy_score(y_test, y_pred)
print(f"Exactitud en el conjunto de prueba: {accuracy:.4f}")

Exactitud en el conjunto de prueba: 0.5558


In [ ]:
# Reporte detallado de métricas
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))


Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.79      0.89      0.84       980
           1       0.85      0.95      0.90      1135
           2       0.90      0.26      0.40      1032
           3       0.71      0.35      0.47      1010
           4       0.88      0.17      0.29       982
           5       0.55      0.05      0.09       892
           6       0.65      0.93      0.77       958
           7       0.88      0.27      0.42      1028
           8       0.28      0.67      0.40       974
           9       0.37      0.95      0.53      1009

    accuracy                           0.56     10000
   macro avg       0.69      0.55      0.51     10000
weighted avg       0.69      0.56      0.52     10000



In [ ]:
# Matriz de confusión
print("Matriz de confusión:")
print(confusion_matrix(y_test, y_pred))

Matriz de confusión:
[[ 870    0    3    5    2    5   31    1   35   28]
 [   0 1079    2    1    0    0   10    0   38    5]
 [  79   25  266   91    5    2  269    4  271   20]
 [  32   39    6  353    2    3   51    8  409  107]
 [  19    2    5    4  168    7   63    7  210  497]
 [  71   25    1   20    3   44   40    2  586  100]
 [  12   12    3    1    1    7  895    0   26    1]
 [   0   15    2   10    5    1    5  280   39  671]
 [  13   72    3    7    3   11   12    4  648  201]
 [   5    7    3    6    1    0    1   13   18  955]]
